### ISSUE TITLE
Confusing Phabricator Setup Variables

### ISSUE THREAD

**Issue by arkag** [devurandom/phabricator-ldap-sync#1]
Not exactly sure where I should be pulling from to modify these variables. Could I get some help regarding that? And more descriptive comments for those after me?

Variables:

```
define("PHAB_PROJECT_LDAP_DN_FIELD", "std:project:mycustomfield:ldap:dn");
define("PHAB_USER_LDAP_DN_FIELD", "std:user:mycustomfield:ldap:dn");
define("PHAB_USER_ACCOUNT_TYPE", "AccountType");
```

**Comment by ghost** [comment]
## `PHAB_PROJECT_LDAP_DN_FIELD`

You need a field in `projects.custom-field-definitions` that looks something like the following:

``` json
{
  "my-org:ldap:dn": {
    "name": "LDAP DN",
    "type": "text",
    "caption": "DN of the LDAP object to sync with (if any).",
    "required": false,
    "disabled": false,
    "edit": true,
    "view": false
  }
}
```

The fully qualified name of this field, e.g. `std:project:my-org:ldap:dn` in this example, is the one you need to set `PHAB_PROJECT_LDAP_DN_FIELD` to. Only projects which have this field set will be touched by the script - the _project members will be synced_ with the group at the specified LDAP DN.

## `PHAB_USER_LDAP_DN_FIELD`

This is the same as `PHAB_PROJECT_LDAP_DN_FIELD`, but for users instead of projects. This is currently completely _unused_ - you can defined it to any non-empty string. You don't even need to define a custom field in your Phabricator config as modifying users with information from LDAP (e.g. name or similar) is currently _not implemented_.

I defined it in our setup, but never used it - there are no users on our install that have it set.

## `PHAB_USER_ACCOUNT_TYPE`

This is a _filter_ for users that the script considers _when adding/removing users to/from groups_. Only Phabricator accounts with this type will be touched, all others will be left alone. This is necessary even if you don't want individual users to be modified (s.a.).

In our install this is set to `RemoteUser`, because all our LDAP users are setup using [the RemoteUser Phabricator extensions](https://github.com/uhd-urz/phabricator-extensions-remoteuser). If you manage your Phabricator users using the built-in LDAP capabilities, this string will be `ldap`. Have a look at `getAdapterType()` in `libphutil/src/auth/Phutil*AuthAdapter.php` for other possible values.

**Comment by arkag** [comment]
I don't have that set in my instance.

```
{
  "my-org:ldap:dn": {
    "name": "LDAP DN",
    "type": "text",
    "caption": "DN of the LDAP object to sync with (if any).",
    "required": false,
    "disabled": true,
    "edit": true,
    "view": false
  }
}
```

Would doing this be sufficient? All I set was the `disabled` option to true.
EDIT: I may be misunderstanding what that is set for. Sorry.

Also, we connect to ldap as an anonymous user, do I need to set anything special to ensure the script works as intended or will it make a proper request without it?

**Comment by ghost** [comment]
If it is `disabled`, you cannot edit it (i.e. set it for the projects you want to sync). I am not sure whether Phabricator will make the contents available to scripts in this case, either. I.e. I don't think disabling the field makes sense. It is already not shown to users (`view: false`) and only shown in the edit screen of projects (`edit: true`). Have a look at the custom-fields documentation of Phabricator for more details.

I suggest replacing `my-org` with `basilosaurus` or the name of your organisation, to prevent name clashes in case some extension decides to add a field of the same name.

**Comment by arkag** [comment]
Ah, that helps. Thank you. How exactly am I setting this? Can I do it via cli?

**Comment by ghost** [comment]
https://secure.phabricator.com/book/phabricator/article/custom_fields/
